cc_binary(
        name="browser",
        srcs=[
                "main.cc", "util.h", "parse/html.h", "parse/html.cc"
        ],
        deps = [
                "@com_github_gflags_gflags//:gflags",
        ],
)