cc_binary(
        name="browser",
        srcs=[
                "main.cc",
                "util.h",
                "parse/html.h",
                "parse/html.cc",
                "parse/parser.h",
                "parse/parser.cc",
                "constants.h"
        ],
        deps = [
                "@com_github_gflags_gflags//:gflags",
        ],
)